version: "3.9"

services:
  app:
    image: node:20-bullseye
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: bash -lc "npm install && node app.js"
    environment:
      MONGODB_URI: mongodb://mongo:27017/dp
      REDIS_PASSWORD: ""
      REDIS_CLUSTER_NODES: redis-cluster:6379,redis-cluster:6380,redis-cluster:6381,redis-cluster:6382,redis-cluster:6383,redis-cluster:6384
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - mongo
      - redis-cluster
    ports:
      - "3000:3000"

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis-cluster:
    image: bitnami/redis-cluster:7
    environment:
      - REDIS_PASSWORD=
      - REDIS_NODES=6
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_CREATOR=yes
    ports:
      - "6379:6379"
      - "6380:6380"
      - "6381:6381"
      - "6382:6382"
      - "6383:6383"
      - "6384:6384"
    volumes:
      - redis-data:/bitnami

volumes:
  mongo-data:
  redis-data:
